//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepresenterImage
    {
        public int id { get; set; }
        public string image { get; set; }
        public int representerId { get; set; }
    
        public virtual Representer Representer { get; set; }
    }
}
